export { USERS_QUERY } from './queries'
export { LOGIN_QUERY } from './queries'
export { PDFS_QUERY } from './queries'
export { TEACHER_PIC_QUERY } from './queries'
export { STUDENT_PIC_QUERY } from './queries'
export { TODOS_QUERY } from './queries'
export { CHATS_QUERY } from './queries'

export { LOGIN_USER_MUTATION } from './mutations'
export { CREATE_USER_MUTATION } from './mutations'
export { SIGNOUT_USER_MUTATION } from './mutations'
export { SINGLE_UPLOAD_PDF_MUTATION } from './mutations'
export { DELETE_PDF_MUTATION } from './mutations'
export { TEACHER_PIC_MUTATION } from './mutations'
export { STUDENT_PIC_MUTATION } from './mutations'
export { CREATE_TODO_MUTATION } from './mutations'
export { DELETE_TODO_MUTATION } from './mutations'
export { SEND_MESSAGE_MUTATION } from './mutations'

export { PDF_SUBSCRIPTION } from './subscription'
export { TEACHER_PIC_SUBSCRIPTION } from './subscription'
export { STUDENT_PIC_SUBSCRIPTION } from './subscription'
export { TODO_SUBSCRIPTION } from './subscription'
export { MESSAGE_SENT_SUBSCRIPTION } from './subscription'